### ISSUE TITLE
提个小意见

### ISSUE THREAD

**Issue by cuicsi** [mingzhixian/scrcpy#10]
普通人需要遥控的，其实也就顶多一两台，能不能选择默认的一台进入软件就可以直远程控制。也就是增加一个默认选择的手机。东西很好用，赞

**Comment by mingzhixian** [comment]
已支持

**Comment by cuicsi** [comment]
收到，再提一个小推荐。
能不能有一个最小化的按键点击一下就变成了个悬浮小图标。东西很好，之前请。作者和郭东鹏🥳🥳🥳

**Comment by cuicsi** [comment]
收到，再提一个小推荐。
能不能有一个最小化的按键点击一下就变成了个悬浮小图标。东西很好，之前请作者喝过东鹏🥳🥳🥳
