### ISSUE TITLE
添加修改屏幕密度的设置

### ISSUE THREAD

**Issue by blibilijojo** [mingzhixian/scrcpy#2]
![image](https://user-images.githubusercontent.com/102420734/235202419-29de5500-456f-4e50-82c2-caf9cb373329.png)
![image](https://user-images.githubusercontent.com/102420734/235202496-497bda91-5484-4f11-b47b-cd81312a9e0b.png)
就是希望可以在控制的一堆设置里加一个控制之后的屏幕密度设置，然后结束控制自动复原

**Comment by mingzhixian** [comment]
你好，并不会考虑修改dpi，因为每个手机原始dpi不同，正常退出可以还原，但非正常退出无法使用scrcpy_back实现还原
鉴于主被控端分辨率差异导致字体太小的问题，我会尝试等比改变分辨率的方法

**Comment by mingzhixian** [comment]
你好，修改密度的操作暂时未加入，但加入了不修改分辨率的选项
