### ISSUE TITLE
测试了下，有些控制问题

### ISSUE THREAD

**Issue by cgapk123** [mingzhixian/scrcpy#41]
无论是有线还是无线ADB，全部都只能A设备到B设备画面投屏，而投屏后很多按键，包括三个导航栏，但点击后都没用，只是画面展示，无法任何控制，我记得最新的 Scrcpy 是支持控制呀，并且还可以裁切画面。

**Comment by mingzhixian** [comment]
小米系统需要打开开发者选项的安全调试
另外，易控并不是scrcpy套UI，易控的server是参照scrcpy重新实现的，有些scrcpy的功能易控并不需要，就没有实现，有些易控的功能原scrcpy没有，是自己新加的
