### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by jingbohi** [mingzhixian/scrcpy#42]
编译报错：
D:\easycontrol\app\src\main\java\top\saymzx\easycontrol\app\client\tools\ClientStream.java:72: 错误: 找不到符号
      adb.pushFile(AppData.applicationContext.getResources().openRawResource(R.raw.easycontrol_server), serverName, null);
                                                                              ^
  符号:   变量 raw
  位置: 类 R

**Comment by mingzhixian** [comment]
存在两个模块，server与app，其中server模块是运行于被控端的后端程序，启动时由运行于主控端的app推送过去，因此需要先编译server模块，然后将编译好的server程序放入app模块中，再编译app模块，server模块的gradle有一个自定义任务：copyrelease，执行任务会自动完成编译server并放入app模块的步骤

**Comment by jingbohi** [comment]
不知道是不是自己环境有问题，build server模块提示：
The option setting 'android.defaults.buildfeatures.buildconfig=true' is deprecated.
The current default is 'false'.
It will be removed in version 9.0 of the Android Gradle plugin.
You can resolve this warning in Android Studio via `Refactor` > `Migrate BuildConfig to Gradle Build Files`
Affected Modules: app
而且copyrelease任务不执行

**Comment by mingzhixian** [comment]
环境问题，你按照提示修改一下即可，或者百度一下

**Comment by jingbohi** [comment]
查了半天没有找到有效解决办法，手动复制了文件，编译成功，非常感谢！
