### ISSUE TITLE
播放崩铁的pv的时候卡死

### ISSUE THREAD

**Issue by blibilijojo** [mingzhixian/scrcpy#5]
或许是码率之类的配置问题吗，问一下，他V6.3的默认控制配置是什么

**Comment by mingzhixian** [comment]
![image](https://github.com/mingzhixian/scrcpy/assets/72658846/487c06d2-a2fb-4005-aef7-bd044c4bfdb7)
请问该现象是否可复现，在其他软件播放视频是否存在相似问题？

**Comment by blibilijojo** [comment]
> ![image](https://user-images.githubusercontent.com/72658846/238133313-487c06d2-a2fb-4005-aef7-bd044c4bfdb7.png) 请问该现象是否可复现，在其他软件播放视频是否存在相似问题？

em，复现没有仔细尝试，播放视频没问题
