### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by blibilijojo** [mingzhixian/scrcpy#8]
一个屏幕完全坏了的手机，usb模拟位置啥的关了，无线调试关了，但是开着usb调试，咋才能把无线调试和usb模拟位置再次打开
![image](https://github.com/mingzhixian/scrcpy/assets/102420734/99cd85ad-4124-4f95-ba2c-49a6301cb3e3)

**Comment by blibilijojo** [comment]
没有root

**Comment by blibilijojo** [comment]
就是想要打开“USB调试(安全设置)
”

**Comment by mingzhixian** [comment]
如果以前允许过其他设备调试，那么在该设备上使用scrcpy控制屏幕操作就可以，没有允许过的话不好搞

**Comment by blibilijojo** [comment]
> 如果以前允许过其他设备调试，那么在该设备上使用scrcpy控制屏幕操作就可以，没有允许过的话不好搞

离谱的是网络也关了，无限调试也关了，只有汤姆的一个usb调试开着

**Comment by blibilijojo** [comment]
> > 如果以前允许过其他设备调试，那么在该设备上使用scrcpy控制屏幕操作就可以，没有允许过的话不好搞
> 
> 离谱的是网络也关了，无限调试也关了，只有汤姆的一个usb调试开着

“USB调试(安全设置)”也关着
