### ISSUE TITLE
噢，安卓7不闪退了，但是报错，如下

### ISSUE THREAD

**Issue by lzkk4** [mingzhixian/scrcpy#9]
![Screenshot_2023-06-24-18-37-15-197.jpeg](https://github.com/mingzhixian/scrcpy/assets/67060386/baf4f503-d2a0-4592-bc66-3dbbcf5c2f19)

**Comment by mingzhixian** [comment]
收到，下个版本将修复此问题

**Comment by mingzhixian** [comment]
已修复
